ConsultaRemedios/cr-ui

package.json
src/components/common/BaseCheckbox/BaseCheckbox.vue

Altera a cor de fundo e borda do checkbox para termos um contraste mais acessível.

Altera estilo do checkbox

---

package.json

No pr https://github.com/ConsultaRemedios/cr-ui/pull/4 não foi atualizado a versão no package.json.

Atualiza package.json

---

src/components/common/Autocomplete/Autocomplete.spec.js
src/components/common/Autocomplete/Autocomplete.vue
src/components/common/Autocomplete/__snapshots__/Autocomplete.spec.js.snap

- Adiciona 2 novos slots: `placeholderSuggestion` e `footerListSuggestions`.
- Passa a permitir alterar a cor do background quando o item esta selecionado.
- Adiciona a prop `clearSuggestions` para limpar a variavel `suggestions`.

Adiciona novos slots e props

---

src/components/common/Autocomplete/Autocomplete.spec.js
src/components/common/Autocomplete/Autocomplete.vue
src/components/common/Autocomplete/__snapshots__/Autocomplete.spec.js.snap

- Adiciona o metodo onClick no slot
- Passa o highlighterKey para suggestionsKey
- Passa a escutar a prop term pelo watch

Adiciona onClick e passa a escutar a prop term pelo watch

---

src/styles/colors.css

- Cria arquivo base onde serão adicionados as cores da biblioteca, por meio de variáveis de CSS.

Cria variaveis de cores da biblioteca

---

src/styles/colors.css

- Adicionas cores de textos, como a cor default, e de alguns status da lib.
- Adiciona cores para call to actions.

Adiciona cores nas variáveis do cr-ui

---

config/styleguide/icons-mixin.js
src/icons/refresh.icon.svg

Adiciona ícone de refresh

---

config/styleguide/icons-mixin.js
src/icons/chevron-down.icon.svg
src/icons/chevron-left.icon.svg
src/icons/chevron-right.icon.svg
src/icons/chevron-up.icon.svg
src/icons/next.icon.svg
src/icons/previous.icon.svg

- Adiciona ícones de chevron
- Atualiza ícones de next e previous

Adiciona ícones de chevron

---

.gitignore
config/styleguide/icons-mixin.js
package.json
src/icons/navigation-more.icon.svg

- Adição do @babel/preset-env no `resolutions` do package.json
- Adição do ícone mais navegação

Novo ícone de mais navegação

---

src/styles/colors.css

- Adiciona cores das classificações de medicamentos nas variáveis.

Adiciona cores das classificações

---

src/components/common/SkeletonPlaceholder/SkeletonPlaceholder.md
src/components/common/SkeletonPlaceholder/SkeletonPlaceholder.spec.js
src/components/common/SkeletonPlaceholder/SkeletonPlaceholder.vue
src/components/common/SkeletonPlaceholder/__snapshots__/SkeletonPlaceholder.spec.js.snap
src/components/common/SkeletonPlaceholder/index.js
src/script.js
src/styles/components/skeleton-placeholder.css

Adiciona component para gerar placeholder content. 
Foi criado um css separado do vue para conseguirmos usar apenas o css em outros lugares.

Adiciona component para placeholder content

---

src/styles/colors.css

Nova cor para borda.

---

config/styleguide.config.js
src/components/common/BaseRadioButton/BaseRadioButton.vue
src/styles/colors.css

Altera o estilo do RadioButton que vai ser utilizado nas modais OfferShippingMethos, ShippingMethodsModal e DefaultDeliveryAddress.

BaseRadioButton atualizado

---

.github/pull_request_template.md
.github/workflows/pr-name.yml
CHANGELOG.md
commitlint.config.js
package.json
yarn.lock

configura commitlint, commitzen e standard-version para geração automática de changelogs baseado nas
mensagens de commit
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I283

chore(commits): configura commitlint, commitzen e standard-version

---

.github/pull_request_template.md

A extensão pro chrome que criamos pra validar os PRs espera que a keyword seja `task` e não `ref`.
...

chore: atualiza template de PRs

---

src/styles/colors.css

Estamos precisando de uma variável para colocar a cor do `text-info` em bordas, esse PR tem como objetivo adicionar essa nova variável.
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I483
Não se aplica.
Não se aplica.
Não se aplica.

feat: adiciona nova variável de cor

---

src/components/common/BaseTooltip/BaseTooltip.spec.js
src/components/common/BaseTooltip/BaseTooltip.vue

adiciona tooltip no document apenas quando a prop  show é true
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I514

perf(basetooltip): adiciona tooltip no document apenas quando necessário 

---

src/components/cr/StoreModal/StoreModal.spec.js
src/components/cr/StoreModal/StoreModal.vue

emit evento quando o usuário clicar no botão `Ver mais produtos da loja`
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I438

feat: emit evento quando o usuário clica no botão

---

src/components/common/BaseCheckbox/BaseCheckbox.vue

Mudamos o estilo do checkbox desabilitado
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I503
...

style: muda o estilo do checkbox desabilitado

---

src/components/common/BaseCheckbox/BaseCheckbox.vue

acidentalmente o PR for mergeado com códigos desnecessário
This reverts commit 078e61ba2033d98da545e4e5c37887f79c984fb1.
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I503

chore: revert "style: muda o estilo do checkbox desabilitado (#76)"

---

src/components/common/BaseCheckbox/BaseCheckbox.vue

Mudamos o estilo do checkbox desabilitado
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P10/I503
...

feat: altera o layout do checkbox desabilitado

---

src/components/cr/RemovedItemsModal/RemovedItemsModal.md
src/components/cr/RemovedItemsModal/RemovedItemsModal.spec.js
src/components/cr/RemovedItemsModal/RemovedItemsModal.vue
src/components/cr/RemovedItemsModal/index.js

Este PR visa adicionar a modal que exibe itens removidos do carrinho em caso de falta de estoque ou qualquer outro motivo (vindo do backend)
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P21/I367
...

feat: adiciona modal que exibe itens removidos do carrinho por falta de estoque

---

src/script.js

Este PR visa exportar nova modal que havia sido criada no PR anterior.
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P21/I367
...

refactor: exporta nova modal de items removidos do carrinho no script

---

src/components/cr/RemovedItemsModal/RemovedItemsModal.md
src/components/cr/RemovedItemsModal/RemovedItemsModal.vue
src/script.js

Este PR visa ajusta markdown e estilo de modal nova de items removidos.
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P21/I367
...

refactor: corrige markdown e estilo de nova modal 

---

src/components/cr/ZipcodeForm/ZipcodeForm.md
src/components/cr/ZipcodeForm/ZipcodeForm.spec.js
src/components/cr/ZipcodeForm/ZipcodeForm.vue

Neste PR foi adicionado o Autocomplet ao componente ZipcodeForm.vue.
task: https://sprints.zoho.com/team/consultaremedios#itemdetails/P32/I40
...

feat: adiciona autocomplet no componente ZipcodeForm.vue
